language: python
cache:
  - apt
  - pip
python:
  - "2.7"
services:
  - postgresql
  - elasticsearch
  - rabbitmq
addons:
  postgresql: "9.4"
  apt:
    packages:
      - python-software-properties
      - libtesseract-dev
      - poppler-utils
      - libreoffice
      - djvulibre-bin
env:
  global:
    - ALEPH_TEST_SETTINGS=$TRAVIS_BUILD_DIR/test_settings.py
    - OAUTH_KEY=fake
    - OAUTH_SECRET=fake
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y tesseract-ocr-eng readpst
  - wget --quiet https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.stretch_amd64.deb
  - dpkg -i wkhtmltox_0.12.5-1.stretch_amd64.deb
  - rm wkhtmltox_0.12.5-1.stretch_amd64.deb


install:
  - gem install sass
  - pip install --upgrade setuptools pip
  - pip install -r requirements.txt
  - pip install -e .
  - pip install psycopg2 coveralls
  - npm install -g bower uglifyjs
  - bower install
before_script:
  - psql -c 'create database aleph_test;' -U postgres
  - cp $TRAVIS_BUILD_DIR/test_settings.py.tmpl $TRAVIS_BUILD_DIR/test_settings.py
  - nosetests --version
  - psql --version
script:
  - nosetests --with-coverage --cover-package=aleph
after_success:
  - coveralls
